### ISSUE TITLE
Can't finalize the liability with zero cost

### ISSUE THREAD

**Issue by XomakNet** [airalab/robonomics_contracts#42]
_Finalize_ method fails for zero cost liabilities due to ERC20 transfer call with zero value.

**Comment by akru** [comment]
Basically protocol don't permit zero-cost transaction, but discussion can be started here. Can you explain your position around this issue.

**Comment by akru** [comment]
Fixed in https://github.com/airalab/robonomics_contracts/commit/cf1a5bd64214bcfcc8c11bd33f810c06f242a20f
