### ISSUE TITLE
XRT deposit to Main XRT adress

### ISSUE THREAD

**Issue by Bazinga66** [airalab/robonomics_contracts#58]
Good day,

I made a mistake to withdraw funds from Bilaxy Exchange to your adres. 

Txid :

0xc5b05c9fea9569f5e9ca7cfe69e08e149dce0cd6c2bfcb3e4201b0f03875d599

from : 

0x253ff8d3b639243e2c9c4a36a4c461aa7fc5fe0d

Number of XRT coins : 21.892052 

Can you guys help me out? 

Thanks in advance,

Roy

**Comment by ensrationis** [comment]
Please wait some time before we will discuss that

**Comment by Bazinga66** [comment]
Hi,

What time do you guys think you need?

Best regards

**Comment by akru** [comment]
Hello @Bazinga66, unfortunately it’s technically impossible to withdraw any ERC20 from token contract, the team have no any privileged actions on it. Feel free to check contract sources https://etherscan.io/address/0x7de91b204c1c737bcee6f000aaa6569cf7061cb7#code

deposit some ERC20 on XRT contract, technically is same as deposit on 0x000000000… or any unavailable address.
