### ISSUE TITLE
$XRT sent to token contract address

### ISSUE THREAD

**Issue by Leemo94** [airalab/robonomics_contracts#59]
A user accidently sent their XRT tokens to the actual XRT Contract address: https://etherscan.io/tx/0xa4a3226a4ac727f2787da0436a9bb372e03c6f4eed1cf1b2c0863294b0ebd5bb

They were hoping to use the exodus bridge so that they could begin staking.

It is possible to reinburse / compensate this user?

**Comment by corin2da** [comment]
{
  "address": "0xECa3C88Ef0c24A8Ee89B6Fa645156dc5D748Fe82",
  "msg": "Incorrect transaction hash: 0xa4a3226a4ac727f2787da0436a9bb372e03c6f4eed1cf1b2c0863294b0ebd5bb\nTarget Robonomics parachain address:\n4EuuRhLVdEqhKZ3fzpE5CFtVfWc5mKFuYYPFF38QHPpZC3hd",
  "sig": "0xfdae17a549e7a308a735e62ac8ca59a92819932759bfaf3c3498d4d5c8bb126270a420a3ed4ae859784bef160c1beb7dea766b01abe3db0f3af7d2dc3d38cb001b",
  "version": "2"
}

**Comment by dergudzon** [comment]
Hello! 
![image](https://user-images.githubusercontent.com/6820574/143006543-824fe31a-f275-492f-ad6b-ce9248fcbd49.png)
Try not to use line breaks in the message. Please, use just one line.

Also, I see that ethereum addresses in the transaction and in the message not the same. They have different case of some letters. This is very important for us, please note that addresses should be equal.

**Comment by corin2da** [comment]
{
  "address": "0xECa3C88Ef0c24A8Ee89B6Fa645156dc5D748Fe82",
  "msg": "Incorrect transaction hash: 0xa4a3226a4ac727f2787da0436a9bb372e03c6f4eed1cf1b2c0863294b0ebd5bb Target Robonomics parachain address: 4EuuRhLVdEqhKZ3fzpE5CFtVfWc5mKFuYYPFF38QHPpZC3hd",
  "sig": "0xd972de48b523315241fe89f9b908991cbfef4323d781d627fbbb1e253c086b3c66a2897ebbcca7cd6e8b2dae4f79a47fb3525ba93750ae22ebcc350edec480ac1c",
  "version": "2"
}

**Comment by dergudzon** [comment]
Message Signature Verified: https://etherscan.io/verifySig/3776
 
 We'll add 4,002.884277353XRT to the address 4EuuRhLVdEqhKZ3fzpE5CFtVfWc5mKFuYYPFF38QHPpZC3hd

**Comment by akru** [comment]
Executed at https://parachain.robonomics.network/?rpc=wss%3A%2F%2Fmain.frontier.rpc.robonomics.network%2F#/explorer/query/0xe1d54d4cae8c3a9da89a2680d9b1262b47c82bb83dd42c1de968afcc67f39642
